import type { Job } from "@/components/freelancer/dashboard/types";

export const MOCK_JOBS: Job[] = [
  {
    id: "job-1",
    title: "Build a Modern E-commerce Website with Next.js",
    description:
      "We need a skilled frontend developer to build a responsive e-commerce platform using Next.js, Tailwind CSS, and Stripe integration. Must have experience with product catalogs, cart functionality, and checkout flows.",
    budget: 2500,
    budgetType: "fixed",
    skills: ["Next.js", "TypeScript", "Tailwind CSS", "Stripe"],
    clientName: "Sarah Chen",
    clientAvatar: "SC",
    postedAt: "2026-05-03",
    proposals: 12,
    saved: false,
  },
  {
    id: "job-2",
    title: "Mobile App UI/UX Design for Fitness Tracker",
    description:
      "Looking for a talented UI/UX designer to create wireframes and high-fidelity mockups for a fitness tracking mobile app. Should support iOS and Android design patterns. Figma preferred.",
    budget: 1800,
    budgetType: "fixed",
    skills: ["Figma", "UI/UX", "Mobile Design", "Prototyping"],
    clientName: "Marcus Johnson",
    clientAvatar: "MJ",
    postedAt: "2026-05-02",
    proposals: 8,
    saved: false,
  },
  {
    id: "job-3",
    title: "Python Backend API Development with FastAPI",
    description:
      "Need an experienced Python developer to build RESTful APIs using FastAPI for our SaaS platform. Must include authentication, role-based access control, and comprehensive documentation.",
    budget: 3200,
    budgetType: "fixed",
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
    clientName: "Elena Rodriguez",
    clientAvatar: "ER",
    postedAt: "2026-05-01",
    proposals: 15,
    saved: false,
  },
  {
    id: "job-4",
    title: "WordPress Plugin Development for Booking System",
    description:
      "We need a custom WordPress plugin that handles appointment booking with calendar integration, email notifications, and payment processing via PayPal and Stripe.",
    budget: 1200,
    budgetType: "fixed",
    skills: ["WordPress", "PHP", "JavaScript", "MySQL"],
    clientName: "David Kim",
    clientAvatar: "DK",
    postedAt: "2026-04-30",
    proposals: 6,
    saved: false,
  },
  {
    id: "job-5",
    title: "Data Visualization Dashboard with React & D3.js",
    description:
      "Looking for a developer to build an interactive analytics dashboard with charts, graphs, and real-time data updates. Must use React and D3.js with responsive design.",
    budget: 2000,
    budgetType: "fixed",
    skills: ["React", "D3.js", "TypeScript", "Chart.js"],
    clientName: "Ahmed Hassan",
    clientAvatar: "AH",
    postedAt: "2026-04-29",
    proposals: 9,
    saved: false,
  },
  {
    id: "job-6",
    title: "AI Chatbot Integration with OpenAI API",
    description:
      "Integrate an AI-powered chatbot into our customer support platform using the OpenAI API. Must handle context-aware conversations, fallback responses, and admin analytics.",
    budget: 2800,
    budgetType: "fixed",
    skills: ["OpenAI API", "Node.js", "TypeScript", "WebSocket"],
    clientName: "Lisa Park",
    clientAvatar: "LP",
    postedAt: "2026-04-28",
    proposals: 20,
    saved: false,
  },
  {
    id: "job-7",
    title: "Flutter Mobile App for Food Delivery",
    description:
      "Need a Flutter developer to build a cross-platform food delivery app with real-time order tracking, push notifications, and integration with payment gateways.",
    budget: 4000,
    budgetType: "fixed",
    skills: ["Flutter", "Dart", "Firebase", "Google Maps API"],
    clientName: "Tom Wilson",
    clientAvatar: "TW",
    postedAt: "2026-04-27",
    proposals: 14,
    saved: false,
  },
  {
    id: "job-8",
    title: "DevOps Setup — CI/CD Pipeline with GitHub Actions",
    description:
      "Set up a complete CI/CD pipeline using GitHub Actions, Docker, and AWS for our microservices architecture. Include automated testing, staging environments, and deployment scripts.",
    budget: 1500,
    budgetType: "fixed",
    skills: ["GitHub Actions", "Docker", "AWS", "DevOps"],
    clientName: "Nina Patel",
    clientAvatar: "NP",
    postedAt: "2026-04-26",
    proposals: 7,
    saved: false,
  },
  {
    id: "job-9",
    title: "Logo & Brand Identity for Tech Startup",
    description:
      "Design a complete brand identity including logo, color palette, typography, and brand guidelines for an AI-powered productivity startup. Modern and minimalist style preferred.",
    budget: 800,
    budgetType: "fixed",
    skills: ["Logo Design", "Branding", "Adobe Illustrator", "Figma"],
    clientName: "James Carter",
    clientAvatar: "JC",
    postedAt: "2026-04-25",
    proposals: 18,
    saved: false,
  },
  {
    id: "job-10",
    title: "MERN Stack Developer for SaaS Dashboard",
    description:
      "Looking for a full-stack MERN developer to build the main dashboard for our SaaS product. Must include user management, analytics, and subscription billing with Stripe.",
    budget: 3500,
    budgetType: "fixed",
    skills: ["React", "Node.js", "MongoDB", "Express", "Stripe"],
    clientName: "Sophie Laurent",
    clientAvatar: "SL",
    postedAt: "2026-04-24",
    proposals: 22,
    saved: false,
  },
  {
    id: "job-11",
    title: "SEO Optimization & Performance Audit",
    description:
      "Conduct a full SEO audit of our website and implement improvements including meta tags, structured data, Core Web Vitals optimization, and sitemap generation.",
    budget: 600,
    budgetType: "fixed",
    skills: ["SEO", "Google Analytics", "Technical Writing", "HTML"],
    clientName: "Chris Morgan",
    clientAvatar: "CM",
    postedAt: "2026-04-23",
    proposals: 5,
    saved: false,
  },
  {
    id: "job-12",
    title: "TypeScript Migration for Legacy React Codebase",
    description:
      "We have a large React JavaScript codebase (~50k lines) that needs to be migrated to TypeScript. Must maintain backward compatibility and add proper type definitions throughout.",
    budget: 5000,
    budgetType: "fixed",
    skills: ["TypeScript", "React", "JavaScript", "Webpack"],
    clientName: "Olivia Brown",
    clientAvatar: "OB",
    postedAt: "2026-04-22",
    proposals: 11,
    saved: false,
  },
];

export const MOCK_APPLIED_JOB_IDS = new Set(["job-1", "job-5"]);
